# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d561ec8565ce3a7dc1bfd77b403ec19a814553fd904d00e815c80fe8153e553423c30a9630d01bf7dc271afd9ac6842f01a55ea9d453c854cb79517425950d

test:
  secret_key_base: 968d2fc91d747c52b2ee4ad5dc38d2fa76494ffd1f39542e7625c03ccd4dce6a6c298b9e9251f7b578b4723d4b08c62873e090f04b5b8fc19be6af968d7e8e78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
